version: "3"

services:
  kasyore-backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    working_dir: /usr/kasyore
    tty: true
    ports:
      - 9999:9999
    volumes:
      - ./:/usr/kasyore
    entrypoint: python main.py
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}

  elasticsearch:
    build:
      context: .
      dockerfile: vector_indexer/elasticsearch/Dockerfile.jp
      args:
        - ELASTIC_VERSION=${ELASTIC_VERSION}
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es1vol:/usr/share/elasticsearch
    ports:
      - 9200:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sk http://localhost:9200/ | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kasyore-frontend:
    build:
      context: src/frontend/svelte
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://kasyore-backend:9999/search
      - PORT=5173
    ports:
      - 5173:5173

  db:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./src/database:/docker-entrypoint-initdb.d
    environment:
      - LANG=ja_JP.utf8
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  kasyore-collector:
    build:
      context: .
      dockerfile: src/collector/Dockerfile
    working_dir: /usr/kasyore-collector
    tty: true
    volumes:
      - ./:/usr/kasyore-collector
    entrypoint: python -u src/collector/main.py
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DBNAME=${POSTGRES_DBNAME}
      - ESA_ACCESS_TOKEN=${ESA_ACCESS_TOKEN}
      - ESA_TEAM_NAME=${ESA_TEAM_NAME}

  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMTJhMDg2MzIzNjRiZGM5MzAyOTkwZWFkMTM5YjVjMWUiLCJ0IjoiNTAwNTI4ZWUtNGNiMC00YmRiLWI5MmEtN2NkODllMGI3NmYyIiwicyI6Ik9EUTFabVExTkRrdFpUaG1NeTAwWVRFMExXSTBObUV0WVRreFlUWTVNR00xWWpRMyJ9


volumes:
  es1vol:
    driver: local
  db-store:
